---
# Thruster joint commands (12)
- ros_topic_name: "/spacestation/thrust/bb_th"
  gz_topic_name: "/model/spacestation/joint/bb_th/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/bl_th"
  gz_topic_name: "/model/spacestation/joint/bl_th/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/br_th"
  gz_topic_name: "/model/spacestation/joint/br_th/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/lth_bb"
  gz_topic_name: "/model/spacestation/joint/lth_bb/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/lth_bf"
  gz_topic_name: "/model/spacestation/joint/lth_bf/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/lth_tb"
  gz_topic_name: "/model/spacestation/joint/lth_tb/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/lth_tf"
  gz_topic_name: "/model/spacestation/joint/lth_tf/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/rth_bb"
  gz_topic_name: "/model/spacestation/joint/rth_bb/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/rth_bf"
  gz_topic_name: "/model/spacestation/joint/rth_bf/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/rth_tb"
  gz_topic_name: "/model/spacestation/joint/rth_tb/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

- ros_topic_name: "/spacestation/thrust/rth_tf"
  gz_topic_name: "/model/spacestation/joint/rth_tf/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL

# IMU sensor
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# GPS (NavSat)
- ros_topic_name: "/navsat"
  gz_topic_name: "/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# Cameras (4 total)
- ros_topic_name: "/front_camera/image"
  gz_topic_name: "/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_camera/camera_info"
  gz_topic_name: "/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/mt1_camera/image"
  gz_topic_name: "/mt1_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/mt1_camera/camera_info"
  gz_topic_name: "/mt1_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_r3_camera/image"
  gz_topic_name: "/solar_r3_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_r3_camera/camera_info"
  gz_topic_name: "/solar_r3_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_l3_camera/image"
  gz_topic_name: "/solar_l3_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_l3_camera/camera_info"
  gz_topic_name: "/solar_l3_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
