---
# Thruster joint commands (12)
- ros_topic_name: "/spacestation/thrust/MT_1_1"
  gz_topic_name: "/model/spacestation/joint/MT_1_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/MT_2_1"
  gz_topic_name: "/model/spacestation/joint/MT_2_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/MT_3_1"
  gz_topic_name: "/model/spacestation/joint/MT_3_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/LTTB_1"
  gz_topic_name: "/model/spacestation/joint/LTTB_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/LTTF_1"
  gz_topic_name: "/model/spacestation/joint/LTTF_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/LBTB_1"
  gz_topic_name: "/model/spacestation/joint/LBTB_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/LBTF_1"
  gz_topic_name: "/model/spacestation/joint/LBTF_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/RTTB_1"
  gz_topic_name: "/model/spacestation/joint/RTTB_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/RTTF_1"
  gz_topic_name: "/model/spacestation/joint/RTTF_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/RBTB_1"
  gz_topic_name: "/model/spacestation/joint/RBTB_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/spacestation/thrust/RBTF_1"
  gz_topic_name: "/model/spacestation/joint/RBTF_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# IMU sensor
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# GPS (NavSat)
- ros_topic_name: "/navsat"
  gz_topic_name: "/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# Cameras (4 total)
- ros_topic_name: "/front_camera/image"
  gz_topic_name: "/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_camera/camera_info"
  gz_topic_name: "/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/mt1_camera/image"
  gz_topic_name: "/mt1_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/mt1_camera/camera_info"
  gz_topic_name: "/mt1_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_r3_camera/image"
  gz_topic_name: "/solar_r3_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_r3_camera/camera_info"
  gz_topic_name: "/solar_r3_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_l3_camera/image"
  gz_topic_name: "/solar_l3_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/solar_l3_camera/camera_info"
  gz_topic_name: "/solar_l3_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
